### ISSUE TITLE
How do I send image to server?

### ISSUE THREAD

**Issue by TanTan-TT** [satya164/react-native-image-chooser#1]
Hi 
The uri result to js end is 

``` javascript
image:', { uri: 'content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F31/ACTUAL/1548463300',
```

But How do I use this uri, send to server and show to users.

**Comment by TanTan-TT** [comment]
@satya164 I found a [package](https://www.npmjs.com/package/react-native-file-transfer-android) to upload file. Do you any better solution to send images to server?
And another question is how to select more than one picture from camera roll?

**Comment by satya164** [comment]
@TanTan-TT In my app, I upload the image to AWS with plain XMLHttprequest. See here - https://github.com/scrollback/io.scrollback.neighborhoods/blob/master/app/containers/image-upload-container.js#L79

I'm using formData as I need to add more fields for AWS. But you can do `ajax.send({ uri });` I think.

**Comment by TanTan-TT** [comment]
@satya164 Thank you so much.
Do you mean XMLHttpRequest can change image uri to bytes when upload to server?

**Is there any solution for selecting multi photo?**

**Comment by satya164** [comment]
@TanTan-TT Yup

I've not tried uploading multiple images. You can try and tell me.

**Comment by satya164** [comment]
May be some way using multi part form data.

**Comment by TanTan-TT** [comment]
@satya164 Sorry, I mean pick up multi photos from photo gallery. Is it possible?

**Comment by satya164** [comment]
@TanTan-TT I'll can try to implement it today.

**Comment by TanTan-TT** [comment]
@satya164 Are you sure following code can work?

``` javascript
formData.append("file", { uri, type });
```

I tried, but it doesn't work. And I googled FormData's API. There has not 'append(string,object)'

**Comment by satya164** [comment]
@TanTan-TT Here is the FormData API - https://developer.mozilla.org/en/docs/Web/API/FormData

```js
const formData = new FormData();

formData.append("file", { uri: "file://path/to/image.png", type: "image/png" });
```

The code I sent you is being used in production and it's working.

**Comment by satya164** [comment]
@TanTan-TT Here is the FormData API - https://developer.mozilla.org/en/docs/Web/API/FormData

``` js
const formData = new FormData();

formData.append("file", { uri: "file://path/to/image.png", type: "image/png" });
```

The code I sent you is being used in production and it's working.

Oh, that is specific to React Native. On the web you append a `File` object.

**Comment by TanTan-TT** [comment]
@satya164 in RN-Android, file uri is like "content://xxxxxx" and without suffix such as png/jpg, should I change it to 
file://path/to/image.png

**Comment by satya164** [comment]
@TanTan-TT No, both types of URIs should work.

**Comment by TanTan-TT** [comment]
@satya164 thanks. And I have another question,
When I send request, server returned an error

**The body of your POST request is not well-formed multipart/form-data**

I debuged a whole day and have not any clue, do you have any clue?

**Comment by satya164** [comment]
@TanTan-TT I don't have a lot of experience with `FormData`, but may be I'll be able to help if you can show me the code to upload from the web. The same code should also work in RN with minor changes.

**Comment by TanTan-TT** [comment]
@satya164 This is my code, my image will be sent to Aliyun OSS, which is like AWS S3

``` javascript
    var data = await ImageChooserModule.pickImage();
    const formData = new FormData();
    var {uri,name} = data;
    const type = "image/" + (name.split(".").pop() || "jpg");
    formData.append("name", '${filename}');
    formData.append("filename", '${filename}');
    formData.append("key", '${filename}');
    formData.append('policy',base64Policy);
    formData.append("OSSAccessKeyId",accessKey); 
    formData.append("success_action_status", "201");
    formData.append('signature',sign);
    formData.append('Content-Type',type);
    formData.append("file",{uri,type,name});
    var request = new XMLHttpRequest();
    request.open("POST", ossHost, true);
    request.onreadystatechange = (status)=>{
      if (request.readyState !== 4) {
        return;
      }
      if (request.status === 200) {
        console.log('success', request.responseText);
      } else {
        console.warn('error',request.responseText); // This code is run, then log error ,The body of your POST request is not well-formed multipart/form-data
      }
    }
    request.onerror = (err) => {console.log('upload image fail:',err)};
    request.send(formData);
```

Thank you for helping me.

**Comment by satya164** [comment]
This part might be the problem?

``` js
formData.append('Content-Type',type);
```

The content type should be `multipart/formdata`, not `image/jpg`. I am not sure if you've to specify it even. Try removing it and see. I was doing something like this with AWS and gave me headache to figure out what was wrong.

**Comment by TanTan-TT** [comment]
@satya164 I tried, not still not works. Is it possible RN API assemble multipart request wrong?

**Comment by satya164** [comment]
@TanTan-TT Did you also try `formData.append('Content-Type', 'multipart/formdata')` ?

**Comment by TanTan-TT** [comment]
@satya164 I noticed there is an additional line compared with browser uploading

```
--d4653e4a-9a5d-42e5-8a49-fcafbe9c673c
content-disposition: form-data; name="file"; filename="ic_menu_white_24dp.png"
Content-Type: image/png
Content-Length: 92
```

**Content-Length: 92**
Is there possible wrong format?

**Comment by satya164** [comment]
@TanTan-TT Best way will be to first try this in a browser. Once we have a working code in browser, if it doesn't behave correctly in React Native, we will know that it's a bug. Do you have a working code in browser?

**Comment by TanTan-TT** [comment]
@satya164 I test it in browser, but not above code, I use another jQuery code to upload the same image, and using the same key and signature, it works. I compare the requests using Charles, and the only difference is  in RN request each "content-disposition" has a **Content-Length** line.

**Comment by satya164** [comment]
@TanTan-TT Hmm... Try testing the above code in browser then. May be it's the problem, but I dunno :(

**Comment by TanTan-TT** [comment]
@satya164 The following code can work in browser

``` javascript
  var formData = new FormData();

    var type = "image/png";

//this.props.groupId +'_1.jpg'
    formData.append("name", name);

    formData.append("key", '${filename}');
    formData.append('policy',base64Policy);
    // formData.append('content-type', type);
    formData.append("OSSAccessKeyId",accessKey);
    formData.append("success_action_status", "200");
    formData.append('signature',sign);
        formData.append("file",document.getElementById('file').files[0]);
//content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F32/ACTUAL/291456277'

    console.log('upload image form:',formData);
    // console.log('upload image file:',Blob);

    var request = new XMLHttpRequest();
    console.log('upload image request:',request);

    request.open("POST", ossHost, true);
    // request.setRequestHeader("content-type", "multipart/form-data");

    request.onreadystatechange = function(status){
      if (request.readyState !== 4) {
        return;
      }

      if (request.status === 200) {
        console.log('success', request.responseText);
      } else {
        console.warn('error',request.responseText);
      }
    }



    // request.onerror = (err) => {console.log('upload image fail:',err)};

    request.send(formData);
    return false;
```

**Comment by TanTan-TT** [comment]
@satya164 I made it! Remove **Content-Lenght** attribute. But change RN's source code

**Comment by satya164** [comment]
Glad you got it to work. What changes did you make? May be we need to fix this in RN?

**Comment by TanTan-TT** [comment]
@satya164 
I have another question
How to get ReactContext in another Activity?
I have a new Activity in RN. And in this Activity, I want to get ReactContext from emitting event to JS side.

My current solution is setting a global variable for ReactInstantManager.
